 Trying BERT Model

In [12]:
!pip install transformers

In [13]:
from transformers import AutoTokenizer

checkpoint1 = "bert-base-cased"
checkpoint2 = "bert-base-uncased"

tokenizer1 = AutoTokenizer.from_pretrained(checkpoint1)
tokenoizer = AutoTokenizer.from_pretrained(checkpoint2)

In [14]:
raw_text = ["I want to learn [MASK]"]

inputs = tokenizer1(raw_text, return_tensors="tf")

In [15]:
print(inputs)

{'input_ids': <tf.Tensor: shape=(1, 7), dtype=int32, numpy=array([[ 101,  146, 1328, 1106, 3858,  103,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 7), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 7), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}


In [16]:
from transformers import TFAutoModel

model1 = TFAutoModel.from_pretrained(checkpoint1)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [17]:
outputs = model1(inputs)
print(outputs)

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 7, 768), dtype=float32, numpy=
array([[[ 0.49609017,  0.02314353,  0.11463759, ..., -0.21608153,
          0.29370606, -0.14056337],
        [ 0.54653716, -0.32815483,  0.56620085, ..., -0.18795606,
          0.18711284,  0.011833  ],
        [ 0.33276224,  0.01471301,  0.20091924, ...,  0.03527424,
         -0.06662059, -0.22134027],
        ...,
        [ 0.371972  , -0.12537983,  0.22067283, ..., -0.04283771,
         -0.03776754,  0.14136484],
        [ 0.2788022 ,  0.07384266,  0.05270509, ..., -0.35961267,
          0.3406902 , -0.26412868],
        [ 0.9195291 ,  0.11617208,  0.37616733, ..., -0.31011662,
          0.73162884, -0.41332942]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-0.6543047 ,  0.5218677 ,  0.9998653 , -0.9933197 ,  0.97619414,
         0.91909707,  0.99158865, -0.99624836, -0.9724437 , -0.6834426 ,
         0.9845815 ,  0.9982